apiVersion: v1
kind: Service
metadata:
  name: db  # This creates the DNS entry "db" inside the cluster
spec:
  type: ClusterIP  # Internal only - no outside access
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgres       # <--- How does it find the right Pod?